### ISSUE TITLE
Patcher Error : Original bytes do not match File: r1delta/r1delta.wpatch Line: 10

### ISSUE THREAD

**Issue by HHsomeHand** [r1atlas/r1atlas#8]
Patcher Error
Original bytes do not match File: r1delta/r1delta.wpatch Line: 10

can't run the game successfully

**Comment by VITALISED** [comment]
If you're also running with BME it could be that; we're incompatible with it. You need to provide a bit more context to your install and setup. I also made a new release just now, you can try that and see if it works
